import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Grok Ghibli - AI Photo to Studio Ghibli Art Transformer',
};

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-6 text-ghibli-primary">Terms of Service</h1>
        <p className="text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        
        <div className="prose prose-lg max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            Welcome to Grok Ghibli. By accessing or using our website and services, you agree to be bound by these Terms of Service ("Terms"). 
            If you do not agree to these Terms, please do not use our services.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Grok Ghibli provides an AI-powered image transformation service that converts user-uploaded photos into artwork in the style of Studio Ghibli animation. 
            The service includes image processing, transformation, and temporary storage of original and transformed images.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            To access certain features of our service, you must create an account. You are responsible for maintaining the confidentiality of your account credentials 
            and for all activities that occur under your account. You agree to:
          </p>
          <ul>
            <li>Provide accurate and complete information when creating your account</li>
            <li>Update your information as necessary to keep it current</li>
            <li>Notify us immediately of any unauthorized use of your account or any other breach of security</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate your account if any information provided is inaccurate, false, or no longer valid, 
            or if you have violated these Terms.
          </p>

          <h2>4. Credit System</h2>
          <p>
            Our service operates on a credit-based system:
          </p>
          <ul>
            <li>Each user receives 30 credits upon registration</li>
            <li>Each image transformation requires one credit</li>
            <li>Credits are automatically reset monthly</li>
            <li>We reserve the right to modify the credit system at any time</li>
          </ul>

          <h2>5. User Content</h2>
          <p>
            By uploading images to our service, you:
          </p>
          <ul>
            <li>Represent that you own or have the necessary rights to use and upload the content</li>
            <li>Grant us a non-exclusive, worldwide, royalty-free license to use, store, and process your images solely for the purpose of providing our services to you</li>
            <li>Understand that your original and transformed images will be temporarily stored on our servers for processing purposes</li>
          </ul>

          <h2>6. Prohibited Uses</h2>
          <p>You agree not to use our service to:</p>
          <ul>
            <li>Upload or transmit any content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable</li>
            <li>Upload content that infringes upon any patent, trademark, trade secret, copyright, or other intellectual property rights of any party</li>
            <li>Upload images containing nudity, explicit sexual content, violence, or harmful content</li>
            <li>Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity</li>
            <li>Interfere with or disrupt the service or servers or networks connected to the service</li>
            <li>Attempt to gain unauthorized access to parts of the service not intended for public access</li>
            <li>Use automated scripts, bots, or other means to access or scrape our service</li>
          </ul>

          <h2>7. Intellectual Property</h2>
          <p>
            The Grok Ghibli service, including its design, graphics, logos, and all software used, is protected by copyright, trademark, and other intellectual property laws. 
            You may not reproduce, copy, distribute, sell, or exploit any portion of our service without our express written permission.
          </p>
          <p>
            All transformed images generated by our service are provided to you for personal use. You own the rights to your transformed images, subject to any rights in the 
            original image and the limitations of these Terms.
          </p>

          <h2>8. Disclaimers and Limitations of Liability</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
            IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
          <p>
            IN NO EVENT SHALL GROK GHIBLI, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR 
            EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
          </p>
          <p>
            We do not guarantee that:
          </p>
          <ul>
            <li>The service will meet your specific requirements</li>
            <li>The service will be uninterrupted, timely, secure, or error-free</li>
            <li>The results that may be obtained from the use of the service will be accurate or reliable</li>
            <li>The quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations</li>
          </ul>

          <h2>9. Indemnification</h2>
          <p>
            You agree to indemnify and hold Grok Ghibli and its affiliates, officers, agents, employees, and partners harmless from any claim or demand, 
            including reasonable attorneys' fees, made by any third party due to or arising out of your use of the service, your violation of these Terms, 
            or your violation of any rights of another.
          </p>

          <h2>10. Modifications to Service and Terms</h2>
          <p>
            We reserve the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice. We shall not be 
            liable to you or to any third party for any modification, suspension, or discontinuance of the service.
          </p>
          <p>
            We may revise these Terms at any time by updating this page. By continuing to access or use our service after those revisions become effective, 
            you agree to be bound by the revised terms.
          </p>

          <h2>11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which we operate, without regard to its conflict of law provisions.
          </p>

          <h2>12. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <p>
            Email: legal@grokghibli.com<br />
            Or visit our <Link href="/contact" className="text-ghibli-primary hover:underline">Contact Page</Link>
          </p>
        </div>
        
        <div className="mt-12 pt-8 border-t border-gray-200">
          <p className="text-gray-600">
            By using our service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </p>
          <div className="mt-4">
            <Link 
              href="/" 
              className="inline-block bg-ghibli-primary text-white px-6 py-2 rounded-md hover:bg-ghibli-primary-dark transition-colors"
            >
              Return to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
} 